### ISSUE TITLE
Job delayed more than trim.recent config disappears from horizon even before it executes

### ISSUE THREAD

**Issue by tiago-sb** [laravel/horizon#723] opened 2019-12-12 20:32 UTC
- Horizon Version: 3.4.2
- Laravel Version: 6.3.0
- PHP Version: 7.2.24
- Redis Driver & Version: predis 4.0.9
- Database Driver & Version: Mysql 5.7.28

### Description:
A queue job with a delay of more than horizon.trim.recent, gets removed from the Recent Jobs list even before it gets executed.

### Steps To Reproduce:

set recents trim to 2 minutes:
```
trim' => [
        'recent' => 2,
        ...
    ],
```

Queue a job with a 5 minutes delay

`MyJob::dispatch()->delay(now()->addMinutes(5));`

After 2 minutes the job disappears from the Recent Jobs list although it has not been executed yet.

Expected result:
The job remains in the Recent Jobs list until 2 minutes after it is executed.
or
The job stays in a "Pending Jobs" list until the delay is reached
or
....something else, just not disappear completely.

NOTE that the job does get executed, which we can confirm by checking the horizon.log file

**Comment by mauri870** [comment] 2019-12-13 11:34
That's expected. The timeout `trim.recent` is aplied when the job is pushed into the queue with a redis expire command, so if it's more then the delay it won't be executed.

**Comment by tiago-sb** [comment] 2019-12-13 11:46
Hi, but that is not what happens: the Job **still** gets executed, even though Horizon lists it nowhere...

**Comment by themsaid** [comment] 2019-12-13 13:54
Horizon stores recent the jobs in a set, it clears that set based on the `trim.recent` value you set and that's not related to the actual queue.

You may want to increase the value of `trim.recent` if you wish to be able to see recent jobs that stay longer.

Closing since it's not a bug, this is by design.

**Closed by themsaid** 2019-12-13 13:54 UTC

**Comment by tiago-sb** [comment] 2019-12-13 14:02
Sorry but I have to disagree (in part).

I give it to you that this is the design of trim.recents, etc, etc but then horizon is failing in providing me a view of the jobs my system is handling.
I can have dozens of delayed jobs still waiting to be attempted the first time and Horizon
does not show this at all!

Happy to report this as different bug or enhancement, but I think this gap will cause confusion to a lot of people (anyone who delays a job more than 120 minutes, actually).

**Comment by themsaid** [comment] 2019-12-13 14:03
We made `trim.recent` configurable so you can set it based on your project needs, seems like your project processes millions of jobs that not enough workers are available to handle pending jobs in time, so you need to increase `trim.recent` to be able to see these jobs.

**Comment by tiago-sb** [comment] 2019-12-13 14:09
The scenario is a bit different: when a specific event happens, a job is queued and delayed to execute at 8pm (business requirement). If the job is queued at 8:01 pm, then it will be executed only after 23h and 59 minutes. (8pm the next day)

Again, my point is not about the behaviour of trim.recents, but about a job "disappearing" from horizon UI before it should.

...maybe having a "Pending Jobs" list would make sense ?
I'll leave it to horizon team...

**Comment by antongorodezkiy** [comment] 2021-11-08 23:38
I think the issue I had today is related so wanted to continue discussion:

    Horizon Version: 5.7.15
    Laravel Version: 8.64.0
    PHP Version: 7.4.11

In "Pending Jobs" inside Horizon I had 2 jobs.
In `redis-cli` by running `zrange app_horizon:pending_jobs 0 -1` I had 48 jobs (including 2 from the Pending Jobs) and all those 48 jobs were executed once I started `./artisan horizon`. "Completed Jobs" contained only 2 jobs that were in "Pending Jobs" before.

That was unexpected at least and actually looks like a bug.
