### ISSUE TITLE
ERROR: A non-numeric value encountered - language issue

### ISSUE THREAD

**Issue by SebastianSchoeps** [laravel/horizon#600] opened 2019-05-27 21:34 UTC
Different issue than #597 

- Horizon Version: 3.2.1
- Laravel Version: 5.8.18
- PHP Version: 7.3.3

### Description:
Running on Valet on MacOS Mojave 10.14.4 - on a German system, and that's the issue.

`exec ps axo %cpu,%mem,command` returns something like
 %CPU %MEM COMMAND
  0,0  0,1 /sbin/launchd
  0,0  0,0 /usr/sbin/syslogd
  0,0  0,1 /usr/libexec/UserEventAgent (System)

The separator in German is a comma. Parsing that fails in SystemProcessCounter. 

### Steps To Reproduce:
"3,4" / 100 ==> "PHP Notice:  A non well formed numeric value encountered"

### Solution
Use "float":
`return ['cpu' => (float) $row->first() / 100, 'mem' => (float) $row->last()];`

**Comment by brunogaspar** [comment] 2019-05-27 21:42
Duplicate of https://github.com/laravel/horizon/issues/597

**Comment by SebastianSchoeps** [comment] 2019-05-27 22:33
As I stated, from my point of view it's another issue. #597 drifted towards Alpine - this is about a decimals separator other than ".".

**Comment by driesvints** [comment] 2019-05-28 06:53
Ping @AJenbo: can we use the solution from above?

**Comment by AJenbo** [comment] 2019-05-28 08:04
Afaik it will loose precision, but I can probably either set the local for the command or do propper parsing of the local specific format to get the correct value. I plan to work on it today so this is good timing 🙂

**Comment by driesvints** [comment] 2019-05-28 08:25
Thanks!

**Comment by tomswinkels** [comment] 2019-06-04 06:03
Same issue? https://github.com/laravel/horizon/pull/606

**Comment by driesvints** [comment] 2019-06-04 08:36
@tomswinkels I believe so.

**Closed by driesvints** 2019-06-04 08:36 UTC
Labels: needs more info
