### ISSUE TITLE
After configuration uri js not run, why?

### ISSUE THREAD

**Issue by jianrun** [laravel/horizon#321] opened 2018-04-13 08:04 UTC
After adding in the config/horizon.php 'uri' => 'admin/horizon' 

browse url admin/horizon successed but js not run, why?

**Comment by xel1045** [comment] 2018-04-13 12:14
Horizon is hard-coded to be installed on the `/horizon/` folder. Thus, you can't change its folder.

**Code References:**
* https://github.com/laravel/horizon/blob/1.0/resources/views/app.blade.php#L6
* https://github.com/laravel/horizon/blob/1.0/resources/views/app.blade.php#L7
* https://github.com/laravel/horizon/blob/1.0/resources/views/app.blade.php#L17
* https://github.com/laravel/horizon/blob/1.0/resources/assets/js/router.js#L8

**Comment by jianrun** [comment] 2018-04-13 14:41
@xel1045  no no no, Instead of changing folders, just change the default route.

https://github.com/laravel/horizon/blob/1.0/src/HorizonServiceProvider.php#L52

I just modified the configuration file (config/horizon.php) to cover it

**Comment by tillkruss** [comment] 2018-08-05 15:38
Duplicate of #245

**Comment by driesvints** [comment] 2018-10-25 15:45
This is indeed a duplication of the above issue so I'm gonna close this one.

**Closed by driesvints** 2018-10-25 15:45 UTC
