### ISSUE TITLE
What if.... we could remove pcntl

### ISSUE THREAD

**Issue by OwenMelbz** [laravel/horizon#363] opened 2018-07-11 07:34 UTC
More of a plead than anything for sanity.

But what would be the chances of removing ext-pcntl requirement from the composer json - maybe see if it can be listed as a recommended to remind people.

I only ask this as when developing on not Linux, it’s a royal pain in the butt having to remember to do —ignore-platform-reqs every time.

I’ve always believed that one of Laravel a strongest suits is the great development experience. And this one is definitely the opposite :(

I know technically it’s wrong to remove it, but maybe it’s the lesser of 2 evils punishing those who are not on Linux xD

**Comment by Chroma91** [comment] 2018-09-21 07:47
You can define something like this in your `composer.json`: 

``` "config": {
    "platform": {
      "ext-pcntl": "7.2",
      "ext-posix": "7.2"
    }
  }```

Where `7.2` has to be the PHP version you're using. When you use `PHP 7.1` it should be `7.1` etc.
Then you don't have to do `—ignore-platform-reqs` every time.

**Comment by driesvints** [comment] 2018-10-25 12:31
Gonna close this as a duplicate of https://github.com/laravel/horizon/issues/170

**Closed by driesvints** 2018-10-25 12:31 UTC
