### ISSUE TITLE
Jobs being run by wrong unrelated horizon instance

### ISSUE THREAD

**Issue by ragingdave** [laravel/horizon#356] opened 2018-06-19 20:06 UTC
In my current setup, there are multiple horizon instances running against a single redis instance. Each horizon instance has not only a unique cache prefix but also a unique horizon prefix, the rest of the settings are mostly default.

The current issue is that queue jobs have the potential for running in a completely unrelated horizon instance. For instance kicking off a job from app1, cache_prefix of 'app1_' and horizon_prefix of 'app1_h:', a second related but separate instance (ex. app2, cache_prefix 'app2_', and horizon_prefix 'app2_h:' is running the job, and potentially silently failing as app1 horizon sees the job as paused, and app2 doesn't even register the job in it's horizon recent jobs so there is no failing/success for that job.

I would have expected that the cache prefix and horizon prefix should have been enough so I'm not sure what else I need to do to make these instances run partitioned.

**Comment by ragingdave** [comment] 2018-09-10 14:50
To more clearly describe the error here is a better example:
An app with the same codebase is deployed to a staging and development server. They are using different cache and horizon prefixes, but will end up pulling queued jobs from the other environment.

**Comment by driesvints** [comment] 2018-10-25 12:42
I believe this is a duplicate of #315. Please check the responses there and see if they help you. If not, feel free to respond back.

**Closed by driesvints** 2018-10-25 12:42 UTC

**Comment by ragingdave** [comment] 2018-10-25 12:46
315 is similar but the case is different, he has horizontally scaled and using multiple redis servers. My case and issue is around having a single redis server handling multiple application queues.

I the original example I gave, I configured everything I could to add a prefix to as much as I could and multiple *different* applications were picking up each other's jobs. They aren't getting picked up multiple times like 315 describes.

**Comment by driesvints** [comment] 2018-10-25 12:49
@ragingdave did you use a different queue for every single app?

Where you change `'queue' => ['default'],` to something different per app.

**Comment by ragingdave** [comment] 2018-10-25 12:58
For 1 application I did due to application requirements, but for the others no. I will give that a shot.

My other question around this is then how does one go about environment based separation? For example, my dev and staging environment, for better or worse, are using most of the same resources including the redis server which drives the queue. Would that mean that I would also need to variablize the queue names to get that separation or is there another way around that?

I guess in general, by default I would have assumed that different applications even against the same resources would have been siloed, which seems to unfortunately not be the case.

**Comment by driesvints** [comment] 2018-10-25 13:05
No, you'll need to separate queues per application if you use the same Redis connection. Just name the queue names after your environment and that should work I believe.

**Comment by moisish** [comment] 2023-05-05 13:16
Coming back to this old issue, I was under the impression that having different HORIZON_PREFIX and different CACHE_PREFIX will make the job being processed by the correct horizon process

**Comment by moisish** [comment] 2025-01-14 10:55
2 years late I can confirm that using cache prefix and horizon prefix does not solve the issue
