### ISSUE TITLE
MaxAttemptsExceededException error

### ISSUE THREAD

**Issue by xyrintech** [laravel/horizon#727] opened 2019-12-17 16:13 UTC
- Horizon Version: 3.0
- Laravel Version: 5.8.33
- PHP Version: 7.3
- Redis Driver & Version: predis 1.1
- Database Driver & Version: Postgres 11.6

### Description:
Max attempts and timeout error. 

`Illuminate\Queue\MaxAttemptsExceededException: App\Jobs\CalculateJob has been attempted too many times or run too long. The job may have previously timed out. in /var/www/laravel/vendor/laravel/framework/src/Illuminate/Queue/Worker.php:601`

I have some set of reporting queries to execute on server but I am getting a very unusual kind of error on Laravel Horizon. The issue mainly is the timeout error irrespective that I have set the timeout to 3601 but sometimes the job fails in just 1 or 2 seconds as run time. Following are 2 examples of same set of job:

ISSUE:
![Screenshot 2019-12-17 at 9 38 34 PM](https://user-images.githubusercontent.com/7784136/71012762-9c633a80-2115-11ea-83e9-320ef1f57ddd.png)

SOME TIMES IT WORKS COMPLETELY FINE:
![Screenshot 2019-12-17 at 9 39 29 PM](https://user-images.githubusercontent.com/7784136/71012864-c3217100-2115-11ea-9e61-8f72a462d72d.png)

I am using 150 workers on my setup and on average it deals approx. 2000 jobs in one hour. 

The job mentioned above deals with approx. 8 SQL queries executed on server. 

The problem only occurs when I am having multiple jobs running on server. If I execute 1 to 2 jobs then I do not see this issue at all. So, this makes me sure that something is wrong with the laravel horizon as the code works completely fine at my end.

### Steps To Reproduce:
There is no specific steps to replicate the problem and this is the main problem. The same thing works sometime and sometimes it does not work. I tried to share the details above, kindly see if this helps.

**Comment by driesvints** [comment] 2019-12-17 16:22
Duplicate of https://github.com/laravel/horizon/issues/683

**Closed by driesvints** 2019-12-17 16:22 UTC
