### ISSUE TITLE
segmentation fault error while executing Horizon

### ISSUE THREAD

**Issue by ErwanGuillon** [laravel/horizon#971] opened 2021-02-18 07:34 UTC
- Horizon Version: 5.7.0
- Laravel Version: 8.28.1
- PHP Version: 7.4.15
- Redis Driver & Version: php redis 5.3.2
- Database Driver & Version: Mysql 8

### Description:

I'm on a Macbook pro m1 and when I launch horizon I get a segmentation fault error. I also tried on a brand new Laravel project with same results. 

I'm not very aware of segmentation fault errors but I can provide more informations if needed.

### Steps To Reproduce:

On a mac m1 :

1. Install php with `brew install php@7.4`
2. Install redis extension with `pecl install redis` (answer no-no-no)
3. Launch horizon with `php artisan horizon`
4. Get `[1]    2299 segmentation fault  php artisan horizon`

Thanks in advance for your help

**Comment by jbrooksuk** [comment] 2021-02-18 11:32
I can confirm this issue using `phpredis`. However, it works fine when using `predis`.

**Comment by driesvints** [comment] 2021-02-18 11:37
Seems like this is an issue with the Redis extension not being fully compatible yet with ARM based Macs. There seems to be work being done in Redis 6.2 which should solve some things. Keep an eye on https://github.com/redis/redis to follow up. Closing this as there's nothing we can do here ourselves really.

**Closed by driesvints** 2021-02-18 11:37 UTC

**Comment by ErwanGuillon** [comment] 2021-02-18 16:57
Thanks for the help it works perfectly with predis.

**Comment by pokgak** [comment] 2021-03-17 10:01
Issue discussing the fix for `phpredis`: https://github.com/phpredis/phpredis/issues/1951

**Comment by dinhkhanh** [comment] 2021-09-11 01:08
Run `pecl install redis` again (reinstall or update) would solve this issue.
