### ISSUE TITLE
Failed jobs page doen't show the jobs

### ISSUE THREAD

**Issue by aglipanci** [laravel/horizon#109] opened 2017-08-31 14:25 UTC
When I navigate into the failed jobs page it only shows the loader and it doen't list any failed jobs even though there are 4 of them and they are retrieved by the API. 

<img width="1437" alt="horizon" src="https://user-images.githubusercontent.com/2675283/29928258-d2f5f4b2-8e68-11e7-963b-762475bdec51.png">

**Comment by themsaid** [comment] 2017-09-01 12:23
I can't replicate this issue, try to republish the assets.

**Comment by aglipanci** [comment] 2017-09-01 12:28
Just did that restarted the horizon and supervisord but it's still the same. Any other idea what I can try?

**Comment by themsaid** [comment] 2017-09-01 12:31
I'm not sure, looks like the axios callback isn't getting executed for some reason. Let's see if more people report this issue.

**Comment by aglipanci** [comment] 2017-09-01 12:34
Thanks, let's see. I have another question non-related to this one: While I have horizon running, should I keep my queue:work process running as it was before or horizon will take care of that too?

**Comment by themsaid** [comment] 2017-09-01 12:34
Horizon takes care of that for you :)

**Comment by wells** [comment] 2017-09-01 13:17
@themsaid I can confirm I'm getting the same result on an Ubuntu 16.04 server. Axios is at least making the request and getting a response with data, but the Vue component remains in a loading state. The oddest part, I have successfully seen a list of failed jobs on this particular horizon instance before.

After examining the redis cache (using medis), it appears that some jobs are stored in redis with an integer based id (i.e. 4678) while others are being stored with a random string id (i.e. fb3AGkybiXix7IvvQRJFmiWEAUD7Q1Ig). My theory is that the jobs with random string ids are the cause for this screen remaining in a loading state.

I've also noticed that not all jobs are added to the recent_jobs zset either. My theory is that this mixed identifier typing is the reason some jobs are not showing up there altogether.

I can confirm that I am only running horizon via supervisor. No queue daemons/workers are running for this application. 

Also in my use case, I'm actually running horizon for two separate apps, each connected to their own redis db (the first on 0 and the second on 1). After running this for a couple days, I'm pretty certain their is no overlap or collision between the horizon instances for these two separate applications.

**Comment by themsaid** [comment] 2017-09-01 13:52
Jobs with string ID are jobs pushed before you install horizon, horizon jobs are integer based. You should have made sure your queue is empty before switching to horizon.

**Comment by wells** [comment] 2017-09-01 14:05
Interesting. So, in my case I have a separate application (queue worker) that runs horizon on behalf of queues dispatched to by other application(s) (they do not currently include horizon as a dependency).

Looks like I need to include horizon as a dependency on any laravel application that dispatches jobs to a horizon queue then. Is that correct?

**Comment by themsaid** [comment] 2017-09-01 14:09
Yes correct, you should let Horizon handles dispatching and running jobs. But I don't think that's the reason failed jobs screen acts weird.

**Comment by wells** [comment] 2017-09-01 14:19
Sorry to branch off topic there. Thanks.

Regarding getting stuck at loading on the failed jobs screen, I still think it has to do with any random string id jobs ending up in the failed_jobs list. 

To confim this, I went into medis and deleted entries with random string ids in the zset of `horizon:failed_jobs`. After this the component showed me all of the other failed jobs immediately.

**Comment by themsaid** [comment] 2017-09-01 14:20
strange, at least the loading indicator should disappear even if no jobs appearing.

**Comment by aglipanci** [comment] 2017-09-02 09:57
Executing FLUSHDB on the redis server fixed the issue and the other failed jobs after that are showing just fine.

**Comment by themsaid** [comment] 2017-09-04 12:24
Ok closing since the issue is apparently a result of mixed Horizon & non-horizon jobs in same queue.

For future reference, make sure all jobs are dispatched while horizon is installed.

**Comment by dimsav** [comment] 2017-10-02 09:40
We still get this issue. The exception thrown is a "Integrity constraint violation" exception (duplicate primary key). 

Running FLUSHDB didn't fix anything.

**Comment by keevitaja** [comment] 2017-11-07 14:47
I have the same issue on forge provisioned server.

**Comment by themsaid** [comment] 2017-11-07 14:49
Can you please try upgrading to 1.0.8 and make sure you re-publish the assets? The new error handler should start showing errors in the browser console which will give us more insights about what's going on.

**Comment by keevitaja** [comment] 2017-11-07 14:59
Did that. This is what i get:

![xs69ykf](https://user-images.githubusercontent.com/158787/32500095-0590c786-c3dd-11e7-8946-415abaaa7953.png)

**Comment by themsaid** [comment] 2017-11-07 15:00
@keevitaja thank you so much, I think I can fix that easily now :)

**Comment by themsaid** [comment] 2018-01-30 17:45
This is now fixed

**Closed by themsaid** 2018-01-30 17:45 UTC

**Comment by robtesch** [comment] 2019-01-08 06:43
Sorry to re-open this so long after it's closed, but I seem to be getting the same/similar issue. I can see horizon is getting the jobs with axios just fine, but the jobs fail to actually display. All jobs appear to have integer IDs, and horizon was working fine before. If there's anything that could be potentially the cause, it might be because I've recently installed Telescope too (but only have that running on local environment, not on production). If there's any extra info you guys might need I am happy to provide it.
