### ISSUE TITLE
Same job picked by multiple workers in multiple servers after 30 seconds

### ISSUE THREAD

**Issue by libern** [laravel/horizon#357] opened 2018-06-22 07:59 UTC
I have a job that is running more than 30 seconds.

By using default config:

In the queue, the job is picked and run correctly at time. However, when the job is stilling running after 30 seconds. Another worker will start to run this same job in exact 30 seconds after first run.

How is this happening?

![image](https://user-images.githubusercontent.com/1830640/41764784-c811b108-7634-11e8-88a1-b468db46b8b9.png)

In the picture above, same job_timestamp means the identifier to the same job.

"Gateway started fetching ..." is the first line of the job when handling.

It is been executed twice after exact 30 seconds.

I found the source code, it appears below, don't know where it is the reason caused this:

![image](https://user-images.githubusercontent.com/1830640/41764805-dbd489cc-7634-11e8-9d61-af43544d6427.png)

**Comment by libern** [comment] 2018-06-22 08:00
#315

**Comment by driesvints** [comment] 2018-10-25 12:36
Duplicate of #315

**Closed by driesvints** 2018-10-25 12:36 UTC
