### ISSUE TITLE
After performing a horizon:terminate, new config is not picked up

### ISSUE THREAD

**Issue by denjaland** [laravel/horizon#213] opened 2017-10-30 11:43 UTC
Hi,

I was under the impression that by running `horizon:terminate`, changes to my .env file would have been picked up.  Apparantly though, it doesn't, and I had to manually trigger `queue:restart`.

Is that expected to be eecuted seperately?  Or is this a bug / missing feature from horizon?

I noticed because I change my database connection credentials, and it wasn't picked up by the queue worker even though I did a rebuild of the config cache, and my app was working, but the jobs were failing.

**Comment by themsaid** [comment] 2017-10-30 14:33
You should have terminated Horizon before changing the .env files to ensure no jobs are already being run

**Comment by denjaland** [comment] 2017-10-30 14:53
I agree, but that doesn't answer the question.
No matter how many times I execute horizon:terminate - the .env variables appear to be cached no matter, even for jobs created well past the update of the .ENV file.

Only a queue:restart did do the job, and had the queues pick up my changed configuration.

**Comment by themsaid** [comment] 2017-10-30 15:54
Well it works for me, changing the .env file and terminating horizon, daemon starts it again and the new configs are picked up correctly. Not sure why it's not working for you, you'll need to track it down a bit.

**Comment by denjaland** [comment] 2017-10-31 10:42
hmm - fair enough - I'll try and investigate some more.

**Comment by OwenMelbz** [comment] 2017-11-09 14:10
@denjaland did you get any further with this? We're having similar issues where it seems like horizon isnt actually quitting the workers

**Comment by denjaland** [comment] 2017-11-09 15:14
Hi @OwenMelbz - unfortunately haven't had the time to investigate.
Adding the explicit `queue:restart` currently solves the issue for us, so less urgent for us now.  I'll try and see if I can further look into it though, but not expecting it ths coming two weeks, unfortunately.

**Comment by pr4xx** [comment] 2017-11-10 19:52
I guess this is related: While tinkering around, it seems that horizon:terminate does not really terminate the running queue workers. I wondered why new dispatched jobs still get handled even though I did a terminate. After using google, I landed here. Only after `queue:restart` no more jobs got handled. Is this intended behavior?
My system: macos, valet, fresh laravel and horizon installation

**Comment by barryvdh** [comment] 2018-01-31 10:44
I also had to add `queue:restart` to my deploy scripts before they were getting picked up.

**Comment by tomcoonen** [comment] 2018-01-31 15:10
Same here, am going to try to add the queue:restart again (replaced it by horizon:terminate when moving to horizon).

**Comment by mdurao** [comment] 2018-01-31 21:07
I was experiencing the same problem and `queue:restart` did the trick!
Should `horizon:terminate` do that?!

**Comment by iquad** [comment] 2018-02-23 13:27
For me, even `queue:restart` did not work.

Had to restart supervisor, seems like working after restart.

**Comment by lionslair** [comment] 2018-09-25 06:02
> supervisorctl restart all

I have similar issues. The first few times things work fine. I get the slack notification that the deployment is finished by forge. However after 1 or two deployments I only get the webhook from my envoy script the deployment had finished. Not from forge.

I updated like you have to restart supervisor and not run the queue:restart It worked. I got the forge completed notification.

`@task('daemons')
    cd {{ $current_release }}
    php artisan horizon:terminate
    supervisorctl restart all
    {{--php artisan queue:restart--}}
@endtask`

Even manually restarting the daemons or queue was working. Will see how this approach fairs. Saves having to do a server reboot after every X deployment.

**Comment by sebastiaanluca** [comment] 2018-10-25 16:04
Can confirm that executing 

```bash
php artisan horizon:purge
php artisan horizon:terminate
```

alone do not make Horizon use updated configuration files. During a deploy to production, we're automatically restarting Horizon using

```bash
sudo supervisorctl stop all
php artisan horizon:purge
php artisan horizon:terminate
sudo supervisorctl start all
```

But locally or without restarting the Supervisor program, a call to `php artisan queue:restart` is required.

IMO the documentation about queue commands is getting a bit confusing —especially with the release of Horizon. Perhaps we can optimize that, or even add one single command to prevent this confusion? We'd first need some clarification on the advised commands to execute though. Should we stop the Supervisor program, purge all jobs, then terminate Horizon … or just purge, terminate, restart … or … Goal would be to accept new jobs, but halt processing of any _during_ deployment and resume (with new codebase and/or database) after. Some additional advise about quickly restarting the queue in a local environment would be welcome too.

**Comment by mfn** [comment] 2018-10-25 19:33
Tested with Laravel 5.7.11 and Horizon 1.4.9, I cannot reproduce this

#### unless

I cache the config. _Then_ environment variable changes don't get picked up.

But without caching the config, every time I issue a `horizon:terminate` it terminates, supervisor starts it again and the new env and config is picked up. I see that Jobs which were already in the queue get executed with the new values.

**Comment by peterlupu** [comment] 2018-10-29 11:41
> Can confirm that executing
> 
> ```shell
> php artisan horizon:purge
> php artisan horizon:terminate
> ```
> 
> alone do not make Horizon use updated configuration files. During a deploy to production, we're automatically restarting Horizon using
> 
> ```shell
> sudo supervisorctl stop all
> php artisan horizon:purge
> php artisan horizon:terminate
> sudo supervisorctl start all
> ```
> 
> But locally or without restarting the Supervisor program, a call to `php artisan queue:restart` is required.
> 
> IMO the documentation about queue commands is getting a bit confusing —especially with the release of Horizon. Perhaps we can optimize that, or even add one single command to prevent this confusion? We'd first need some clarification on the advised commands to execute though. Should we stop the Supervisor program, purge all jobs, then terminate Horizon … or just purge, terminate, restart … or … Goal would be to accept new jobs, but halt processing of any _during_ deployment and resume (with new codebase and/or database) after. Some additional advise about quickly restarting the queue in a local environment would be welcome too.

Hi.

After lots of testing, this seems to be rock solid in production; been running like this for almost an year:

```
// ... artisan down, composer install, migrate etc
php artisan config:cache
php artisan route:cache
php artisan horizon:purge
php artisan horizon:terminate
php artisan queue:restart
php artisan up
```

**Comment by georgeboot** [comment] 2019-01-15 08:59
We had the same issue and came across https://github.com/Supervisor/supervisor/issues/152.

Basically, we updated our Forge daemon to have the path as `/home/forge/site.com` and change the command to `php current/artisan horizon`.

**Comment by driesvints** [comment] 2019-01-28 22:02
@denjaland @sebastiaanluca are you still experiencing this problem? I genuinely believe this is a configuration or deployment step problem and not a problem with Horizon itself.

**Comment by sebastiaanluca** [comment] 2019-01-29 01:03
@driesvints For now I would say it's indeed a deployment issue. Dug a little deeper and found the setup that might cause this. Somewhat similar to @georgeboot's issue, I believe.

For instance, in case of Envoyer and/or zero downtime deployments, the Supervisor job stays active with a previous release of the project —**regardless of any pause, terminate, or purge commands** being executed during deployment. A quick fix seems to be, like mentioned above, to **not** set the Supervisor job path the the _current_ directory, but the project's root directory and navigate to the current directory in the command itself. Another solution is to restart the Supervisor job —after setting the release live— so it navigates to the new release and restarts Horizon.

For example our new Horizon Supervisor .conf file:

```bash
[program:horizon]

process_name=%(program_name)s
directory=/var/www/project
command=/usr/bin/php current/artisan horizon

user=www-data
group=www-data

autostart=true
autorestart=true

stderr_logfile=/var/log/project-horizon.err.log
```

Previously:

```bash
process_name=%(program_name)s
directory=/var/www/project/current
command=/usr/bin/php artisan horizon
```

The latter stays active in the old release and doesn't point to any new release. Simply because Supervisor once navigated to the current dir symlink which was a previous release before our new deployment.

For completeness: we still pause Horizon before migrating and terminate + purge once set live. Will report any additional findings. Thanks for the support!

**Comment by mfn** [comment] 2019-01-29 06:42
> it was a simple user/permissions issue 😶

So is it solved now for you?


> php artisan horizon:terminate should terminate the process and Supervisor should start a new one, right? 

Yes, absolutely.
This is the first thing at which investigation should have stopped. If this doesn't work, the setup itself is wrong in some way.

**Comment by driesvints** [comment] 2019-01-29 12:15
@sebastiaanluca can you try replace the foreach loop in the terminate command with the following and copy/paste the output here while recreating the permission error?

```php
        foreach (array_pluck($masters, 'pid') as $processId) {
            $this->info("Sending TERM Signal To Process: {$processId}");

            posix_kill($processId, SIGTERM);

            if ($error = posix_get_last_error()) {
                $this->error("POSIX error for Process: {$processId}: ".posix_strerror($error));
            }
        }
```

**Comment by driesvints** [comment] 2019-01-29 16:49
@sebastiaanluca I sent in a PR for this: https://github.com/laravel/horizon/pull/485

**Comment by driesvints** [comment] 2019-01-29 16:51
I'm going to close this as this obviously is a configuration/deployment setup issue and not an issue with Horizon itself. This can best be explained in a blog post or a tutorial somewhere. If you feel that anything is missing from the docs for deploying feel free to send in a PR to https://laravel.com/docs/5.7/horizon#running-horizon

**Closed by driesvints** 2019-01-29 16:51 UTC
Labels: bug

**Comment by sbaum2s** [comment] 2025-04-17 14:15
> I'm going to close this as this obviously is a configuration/deployment setup issue and not an issue with Horizon itself. This can best be explained in a blog post or a tutorial somewhere. If you feel that anything is missing from the docs for deploying feel free to send in a PR to https://laravel.com/docs/5.7/horizon#running-horizon

What is the github source for this page? Because for me, now with Laravel 12 Horizont is just as complicated to handle with changed config file as it was years ago.
