### ISSUE TITLE
Horizon does not evenly distribute the queries on SQL Master & Read Replicas

### ISSUE THREAD

**Issue by rennokki** [laravel/horizon#629] opened 2019-07-03 13:40 UTC
- Horizon Version: 3.2.x
- Laravel Version: 5.8.x
- PHP Version: 7.2
- Redis Driver & Version: 5.0.3
- Database Driver & Version: PgSQL 11.2 (AWS)

### Description:
I moved a workload on AWS and i use RDS for PgSQL and EB to deploy the app. Since RDS allows me to create read replicas, i have created one and i put them in the pool in my `config/database.php`. The app can read/write on master and can only read on read replicas.

```
'read' => [
        'host' => [
            'master_fqdn',
            'read_replica_fqdn',
        ],
    ],
    'write' => [
        'host' => [
            'master_fqdn',
         ],
    ],
```

I have ran some workload right now and i have to process more than 4,641 jobs. The thing is that the jobs literally just read data from the DB and create new records based on the data retrieved. Basically, i'm processing insights into a better count-readable format.

The problem is that RDS dashboard shows me that there is a lot of pressure on Master node and no pressure on the Read replica. The first one is the master and the second one is a replica.

![alt text](https://i.imgur.com/Ayatpto.png)

This occurs only when running the workload on jobs. During the full request cycle, it reads and write on according nodes evenly.

### Steps To Reproduce:
1. Deploy a master with a read replica for PgSQL
2. Configure the database to accept multiple hosts for write and read replicas.
3. Put a ton of workload on jobs
4. Watch the queries use only one of the servers (either master or read replica)

**Comment by mfn** [comment] 2019-07-03 13:52
Is this really specific to Horizon?

Seems to me that if this is an issue, it's related to the worker code itself (within the Laravel framework). Can you reproduce this without Horizon, just regular workers?

**Comment by rennokki** [comment] 2019-07-03 13:56
@mfn I opened the issue here because it's hard to understand how Horizon treats this "request cycle" that's documented in the [Database: Getting Started](https://laravel.com/docs/5.8/database) for sticky databases. I assume that enabling the sticky database, it uses the master to read and then to write and it locks it out some way and the rest of the jobs use the same nodes.
Cannot reproduce this at the current time.

**Comment by mfn** [comment] 2019-07-04 03:15
I understand. Running a regular Laravel worker does the same thing. Runs, without interruption, all the time. Never quits unless it crashes or is signaled to do so.

Horizon "just" puts a nice management on top of it, but the basics are the same. That's why I'm asking.

**Comment by driesvints** [comment] 2019-07-04 11:43
I don't have any experience with all this myself I'm afraid so appreciating any help with this.

**Comment by rennokki** [comment] 2019-07-17 06:48
It seems like the order of the pool hosts order matter. If the `master_fqdn` is first, it will always be used in every single job. Swapping the order with the `read_replica_fqdn` will make the read replica fqdn be used every single time.

```
'read' => [
    'host' => [
        'master_fqdn', // this one has prority and will always be used in each job
        'read_replica_fqdn',
    ],
],
'write' => [
    'host' => [
        'master_fqdn',
     ],
],
```

Not to mention that the DB stickyness is `true`, and this might trigger this issue, but i want to use it during each request cycle.

I doubt, but i need confirmation (@taylorotwell, @staudenmeir) that the hosts pool is not randomized or equally balanced. I guess it tries to go for the first available host and will commit the transaction with it.

**Comment by staudenmeir** [comment] 2019-07-17 17:10
If you provide multiple hosts, Laravel orders them randomly and connects to the first (successful) one ([source](https://github.com/laravel/framework/blob/3723becafe0887157bb5beb6aa7ba53ef60855a9/src/Illuminate/Database/Connectors/ConnectionFactory.php#L175)). This host is then used as long as your application/queue worker is running.

> It seems like the order of the pool hosts order matter. If the master_fqdn is first, it will always be used in every single job. Swapping the order with the read_replica_fqdn will make the read replica fqdn be used every single time.

Laravel uses [`shuffle()`](https://php.net/manual/en/function.shuffle.php) for this which is only pseudo-random. With two hosts, you might need a few attempts to see the second host being selected (it works for me).

**Comment by rennokki** [comment] 2019-07-17 17:50
Is there any way I could just re-shuffle it every time the jobs start processing? I understand that the queue worker literally "caches" some config data so it won't bother the config retrieval so much, but it's odd it just gets stuck.

**Comment by staudenmeir** [comment] 2019-07-17 18:37
You would have to disconnect from the database and then reconnect using `DB::disconnect()` or `DB::reconnect()`.

**Comment by driesvints** [comment] 2019-07-18 13:41
Closing this in favor of laravel/framework. Please post an issue there.

**Closed by driesvints** 2019-07-18 13:41 UTC
Labels: needs more info

**Comment by rennokki** [comment] 2019-07-19 06:45
@staudenmeir I was able to replicate the issue your way and it seems like i had to use the `DB::disconnect()` at the very bottom of my jobs.

**Comment by rennokki** [comment] 2019-07-22 20:00
Short brief & explainations here: https://github.com/laravel/framework/issues/29197#issuecomment-513930412
