### ISSUE TITLE
Queue Batches do not work when Cache cluster enabled

### ISSUE THREAD

**Issue by jmarcher** [laravel/horizon#1105] opened 2021-12-16 13:07 UTC
- Laravel Version: 8.67.0
- PHP Version: 8.0.12
- Database Driver & Version: MariaDB 10.6.5 & Redis 6.2 
- PHPRedis: 5.3

### Description:
If you are using cluster cache and a non-clustered connection for Horizon, dispatching a Batch will result in an exception.

### Steps To Reproduce:
Using phpredis as Redis client (as default).

Configure a cluster connection (for cache)
Configure a Horizon connection

Dispatching a Bus::batch() will fail with: `Redis::pipeline(): Can't activate pipeline in multi mode!`

### Ideas
I just saw that the RedisServiceProvider creates a singleton for the RedisManager using the config['client'] value, may it be possible to instance different RedisManagers for each connection inside `config('database.redis')` ? Or am I not seeing something there?

**Comment by driesvints** [comment] 2021-12-20 15:05
I've transferred this to the Horizon repo.

**Comment by driesvints** [comment] 2022-01-24 13:30
@jmarcher I'm gonna have a more thorough look at this soon hopefully. In the meantime can you maybe prepare a repo for me to try out with:

```bash
laravel new bug-report --github="--public"
```

Please make sure that you have the [latest version of the Laravel installer](https://github.com/laravel/installer) in order to run this command. Please also make sure you have both Git & [the GitHub CLI tool](https://cli.github.com) properly set up. Please do not amend and create a separate commit with your custom changes. After you've posted the repository, we'll try to reproduce the issue.

And also list the ENV variables that I should set and prep them a bit some values you're using. I'll then try to recreate the problem myself.

Thanks!

**Comment by driesvints** [comment] 2022-01-27 09:15
Closing this issue because it's inactive, already solved, old or not relevant anymore. Feel to open up a new issue if you're still experiencing this.

**Closed by driesvints** 2022-01-27 09:15 UTC
Labels: needs more info, help wanted

**Comment by driesvints** [comment] 2022-02-04 08:39
Hey @jmarcher, I actually just found out that Horizon doesn't works with clusters at all: https://github.com/laravel/horizon/issues/274#issuecomment-457218217

**Comment by driesvints** [comment] 2022-02-04 14:05
@jmarcher no worries. I think it's best that we leave this be as it seems very much an edge case. I think it could still be related to shared Redis stores somehow...

**Comment by lechatthecat** [comment] 2022-02-16 05:04
> Hey @jmarcher, I actually just found out that Horizon doesn't works with clusters at all: [#274 (comment)](https://github.com/laravel/horizon/issues/274#issuecomment-457218217)

If this is true, I think this must be mentioned in the doc because  laravel queues seems working with clusters.
