### ISSUE TITLE
Error while sending STMT_PREPARE packet. PID=*

### ISSUE THREAD

**Issue by michaelnguyen547** [laravel/horizon#634] opened 2019-07-09 17:00 UTC
- Horizon Version: 3.2.5
- Laravel Version: 5.8.27
- Telescope Version: 2.0.5
- PHP Version: 7.2
- Redis Driver & Version:phpredis 4.3.0

### Description:
I am using Sentry.io which reports the following error "Warning: Error while sending STMT_PREPARE packet. PID=487". It happens 2 to 3 times per day. I notice it started happening after I upgraded from

* Laravel 5.7 -> Laravel 5.8
* Telescope 1.0 -> Telescope 2.0

### Steps To Reproduce:
this bug reported in the background. It may has to do with `Telescope` because telescope shows up in the error stack

```
ErrorException: Warning: Error while sending STMT_PREPARE packet. PID=17107
#35 /vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(61): Doctrine\DBAL\Driver\PDOConnection::prepare
#34 /vendor/laravel/framework/src/Illuminate/Database/Connection.php(326): Illuminate\Database\Connection::Illuminate\Database\{closure}
#33 /vendor/laravel/framework/src/Illuminate/Database/Connection.php(657): Illuminate\Database\Connection::runQueryCallback
#32 /vendor/laravel/framework/src/Illuminate/Database/Connection.php(624): Illuminate\Database\Connection::run
#31 /vendor/laravel/framework/src/Illuminate/Database/Connection.php(333): Illuminate\Database\Connection::select
#30 /vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2124): Illuminate\Database\Query\Builder::runSelect
#29 /vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2318): Illuminate\Database\Query\Builder::Illuminate\Database\Query\{closure}
#28 /vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2598): Illuminate\Database\Query\Builder::onceWithColumns
#27 /vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2320): Illuminate\Database\Query\Builder::pluck
#26 /vendor/laravel/telescope/src/Storage/DatabaseEntriesRepository.php(281): Laravel\Telescope\Storage\DatabaseEntriesRepository::monitoring
#25 /vendor/laravel/telescope/src/Storage/DatabaseEntriesRepository.php(253): Laravel\Telescope\Storage\DatabaseEntriesRepository::loadMonitoredTags
#24 /vendor/laravel/telescope/src/Telescope.php(195): Laravel\Telescope\Telescope::startRecording
#23 /vendor/laravel/telescope/src/ListensForStorageOpportunities.php(57): Laravel\Telescope\Telescope::Laravel\Telescope\{closure}
#22 /vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(347): Illuminate\Events\Dispatcher::Illuminate\Events\{closure}
#21 /vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(196): Illuminate\Events\Dispatcher::dispatch
#20 /vendor/laravel/framework/src/Illuminate/Queue/Worker.php(456): Illuminate\Queue\Worker::raiseBeforeJobEvent
#19 /vendor/laravel/framework/src/Illuminate/Queue/Worker.php(318): Illuminate\Queue\Worker::process
#18 /vendor/laravel/framework/src/Illuminate/Queue/Worker.php(277): Illuminate\Queue\Worker::runJob
#17 /vendor/laravel/framework/src/Illuminate/Queue/Worker.php(118): Illuminate\Queue\Worker::daemon
#16 /vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(102): Illuminate\Queue\Console\WorkCommand::runWorker
#15 /vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(86): Illuminate\Queue\Console\WorkCommand::handle
#14 /vendor/laravel/horizon/src/Console/WorkCommand.php(46): Laravel\Horizon\Console\WorkCommand::handle
#13 [internal](0): call_user_func_array
#12 /vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(32): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}
#11 /vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(90): Illuminate\Container\BoundMethod::callBoundMethod
#10 /vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(34): Illuminate\Container\BoundMethod::call
#9 /vendor/laravel/framework/src/Illuminate/Container/Container.php(576): Illuminate\Container\Container::call
#8 /vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\Console\Command::execute
#7 /vendor/symfony/console/Command/Command.php(255): Symfony\Component\Console\Command\Command::run
#6 /vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Illuminate\Console\Command::run
#5 /vendor/symfony/console/Application.php(921): Symfony\Component\Console\Application::doRunCommand
#4 /vendor/symfony/console/Application.php(273): Symfony\Component\Console\Application::doRun
#3 /vendor/symfony/console/Application.php(149): Symfony\Component\Console\Application::run
#2 /vendor/laravel/framework/src/Illuminate/Console/Application.php(90): Illuminate\Console\Application::run
#1 /vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(133): Illuminate\Foundation\Console\Kernel::handle
#0 /artisan(35): null
```

**Comment by driesvints** [comment] 2019-07-11 13:25
Probably a duplicate of https://github.com/laravel/framework/issues/28920

**Comment by michaelnguyen547** [comment] 2019-07-11 16:05
@driesvints I agree. Most likely has to do with Laravel 5.8. I never had this issue on Laravel 5.7.

**Comment by driesvints** [comment] 2019-07-12 11:34
I'm gonna close this in favor of https://github.com/laravel/framework/issues/28920 so let's continue the discussion there.

**Closed by driesvints** 2019-07-12 11:34 UTC
Labels: needs more info
