### ISSUE TITLE
ERROR: A non-numeric value encountered

### ISSUE THREAD

**Issue by flamingomedia** [laravel/horizon#597] opened 2019-05-22 16:39 UTC
- Horizon Version: 3.2.1
- Laravel Version: 5.7.28
- PHP Version: 7.1.26
- Redis Driver & Version: predis 1.1.1
- Database Driver & Version: mysql 5.7

### Description:
When launching `php artisan horizon`, after the installation steps listed in the documentation, the system works but keeps throwing this Exception every second or so:

```
{
   "class": "ErrorException",
   "message": "A non-numeric value encountered",
   "code": 0,
   "file": "\/var\/www\/vendor\/laravel\/framework\/src\/Illuminate\/Support\/Collection.php:1682",
   "trace": [
       "\/var\/www\/vendor\/laravel\/framework\/src\/Illuminate\/Support\/Collection.php:1682",
       "{\"function\":\"Illuminate\\\\Support\\\\{closure}\",\"class\":\"Illuminate\\\\Support\\\\Collection\",\"type\":\"->\",\"args\":[0,{\"cpu\":0.47,\"mem\":\"www\"}]}",
       "\/var\/www\/vendor\/laravel\/framework\/src\/Illuminate\/Support\/Collection.php:1415",
       "\/var\/www\/vendor\/laravel\/framework\/src\/Illuminate\/Support\/Collection.php:1683",
       "\/var\/www\/vendor\/laravel\/horizon\/src\/Repositories\/RedisSupervisorRepository.php:129",
       "{\"function\":\"Laravel\\\\Horizon\\\\Repositories\\\\{closure}\",\"class\":\"Laravel\\\\Horizon\\\\Repositories\\\\RedisSupervisorRepository\",\"type\":\"->\",\"args\":[\"[object] (Predis\\\\Pipeline\\\\Pipeline)\"]}",
       "\/var\/www\/vendor\/predis\/predis\/src\/Pipeline\/Pipeline.php:211",
       "\/var\/www\/vendor\/predis\/predis\/src\/Client.php:445",
       "\/var\/www\/vendor\/predis\/predis\/src\/Client.php:396",
       "\/var\/www\/vendor\/predis\/predis\/src\/Client.php:418",
       "\/var\/www\/vendor\/laravel\/framework\/src\/Illuminate\/Redis\/Connections\/Connection.php:114",
       "\/var\/www\/vendor\/laravel\/framework\/src\/Illuminate\/Redis\/Connections\/Connection.php:214",
       "\/var\/www\/vendor\/laravel\/horizon\/src\/Repositories\/RedisSupervisorRepository.php:138",
       "\/var\/www\/vendor\/laravel\/horizon\/src\/Supervisor.php:354",
       "\/var\/www\/vendor\/laravel\/horizon\/src\/Supervisor.php:308",
       "\/var\/www\/vendor\/laravel\/horizon\/src\/Supervisor.php:267",
       "\/var\/www\/vendor\/laravel\/horizon\/src\/Console\/SupervisorCommand.php:92",
       "\/var\/www\/vendor\/laravel\/horizon\/src\/Console\/SupervisorComman…
```

I was able to fix it temporarily by updating
`vendor/laravel/horizon/src/SystemProcessCounter.php` at line 33:

```
return ['cpu' => $row->first() / 100, 'mem' => $row->last()];
```

to

```
return ['cpu' => $row->first() / 100, 'mem' => (float)$row->last()];
```

It probably can be fixed in a better way, but that's the spot where it was breaking, by sending 0.00 instead of "0.00".
Looking forward to an update to avoid having to manually change my vendor files. O_o :D

### Steps To Reproduce:
- Install Redis
- Install Horizon
- Launch php artisan horizon

**Comment by lionslair** [comment] 2019-05-23 03:19
Same here

**Comment by bkuhl** [comment] 2019-05-23 12:10
This has killed our production environment.  We're seeing this on alpine v3.8.

**Comment by bkuhl** [comment] 2019-05-23 12:31
A little more digging here shows that https://github.com/gliderlabs/docker-alpine/issues/173#issuecomment-218620191 contains the answer for alpine linux users.  Why this has worked for me up until this point I don't know.

**Comment by AJenbo** [comment] 2019-05-24 15:25
The reason that it has worked previously with the buss box versions of `ps` is that it ignores invalid (unsupported) arguments and just gives you the default. The reason it has worked previously is that Horizon only cared about the line containing the command, but now that it parses the output it needs to actually be what was requested.

The right solution like @bkuhl suggested is to install a more featureful version of `ps`, of cause it would be nice if it fails gracefully. @driesvints would you be ok with it showing `0.00` when a supported version of `ps` is not used, or should I try to make it so that it shows `--` or `Unsupported` in the UI?

**Comment by bkuhl** [comment] 2019-05-24 15:41
I think `Unsupported` would be good, but it'd be ideal if it provided some guidance on how to resolve it via a tooltip or link to this issue.

**Comment by AJenbo** [comment] 2019-05-24 16:25
Here is what I have in mind:
![image](https://user-images.githubusercontent.com/204594/58342668-50873600-7e51-11e9-8ad6-0d6e2aa42e8c.png)

**Comment by bkuhl** [comment] 2019-05-24 16:45
Sounds great to me!

**Comment by driesvints** [comment] 2019-05-27 18:23
The two dashes is fine. Feel free to send in a PR.

**Comment by robclancy** [comment] 2019-06-12 18:32
I personally love spamming bugsnag with a regression.

**Comment by driesvints** [comment] 2019-06-13 13:35
@robclancy does upgrading to v3.2.2 help? A fix for this was merged in here: https://github.com/laravel/horizon/pull/606

**Comment by driesvints** [comment] 2019-06-13 13:36
I'm keeping open this issue btw for this feature request: https://github.com/laravel/horizon/issues/597#issuecomment-495697594

Feel free to PR that in. 

But the numeric issue should be fixed in v3.2.2

**Comment by AJenbo** [comment] 2019-06-13 14:12
#597 only solves the issues for system where the `ps` version supports the output format, but the system language is set to a locale that uses `,` as the fraction separator.

This issue relates to systems where the installed `ps` doesn't support the requested output. I unfortunately haven't haven't had the needed time to work on the issues as there has been more pressing matters, but hope to have time in about a weeks time.

**Comment by driesvints** [comment] 2019-06-14 12:14
In light of the bugs in the last couple of weeks and the performance hit we've decided to revert the original PR. Please see my answer here: https://github.com/laravel/horizon/pull/589#issuecomment-502085735

**Closed** 2019-06-14 12:14 UTC
Labels: bug

**Comment by sayeedazmal** [comment] 2020-06-04 07:32
i have a some problem please help me not show my login page how can I solve that??
![image](https://user-images.githubusercontent.com/32707648/83728085-d98d9b80-a667-11ea-8777-67b99fce80fe.png)

**Comment by AJenbo** [comment] 2020-06-04 07:47
@sayeedazmal your issue doesn't appear to be related to this topic (or even Laravel Horizon). My guess would be that `$name` is either not a number or maybe even the wrong variable being used.
