### ISSUE TITLE
Scaling delayed or doesn't happen at all

### ISSUE THREAD

**Issue by rafalglowacz** [laravel/horizon#667] opened 2019-09-19 08:28 UTC
- Horizon Version: v3.3.2
- Laravel Version: 5.8.22
- PHP Version: 7.2.4
- Redis Driver & Version: phpredis 4.3.0
- Database Driver & Version: MySQL 5.7.22

### Description:

When Horizon is freshly started and all workers have been scaled down then scaling only happens after the first job finishes (which might be a long time) or, if minProcesses is set to 0, it never happens, no jobs get processed. I thought I was doing something wrong but I asked a colleague to check it for me and he got the same results.

### Steps To Reproduce:

- have a supervisor config like this:
```
'supervisor-3' => [
	'connection' => 'redis',
	'queue' => ['myqueue'],
	'balance' => 'auto',
	'minProcesses' => 1, // or 0
	'maxProcesses' => 10,
	'tries' => 1,
	'timeout' => 24 * 3600,
],
```
- clear Redis for good measure
- start Horizon
- **crucial**: wait for all workers for `myqueue` to scale down to the min number (for instance `watch 'ps faux | grep horizon'`)
- put a job in `myqueue` - make it run for half a minute or so in order to see what happens next
- put another job in `myqueue`
- depending on minProcesses:
  - if it was 1, the second job (and any subsequent job) won't start until the first one is done. After that happens, it'll work as expected. If the workers scale down to minimum now, it'll also work fine. The problem is only with the first job after starting Horizon and initially scaling down to minimum.
  - if it was 0, no worker processes will start and no jobs will be executed

**Comment by driesvints** [comment] 2019-09-27 09:40
I'm not sure myself. @themsaid maybe?

**Comment by rafalglowacz** [comment] 2019-10-03 18:38
A little update - today I tested it with a vanilla installation of Laravel 6.1 and Horizon 3.4. All fresh files, nothing from my work project that could potentially influence it in subtle ways. Same problem. I forgot to mention before that it's all running in Docker, specifically Laradock. 

@driesvints You labelled the issue as *needs more info*. What kind of information should I provide?

**Comment by driesvints** [comment] 2019-10-03 19:09
@rafalglowacz it's just that I don't know if this is a bug or not. I needs to be investigated more before we label it as a bug.

**Comment by rafalglowacz** [comment] 2019-10-04 21:18
I've investigated the issue, here are my findings.

The problem is in the `numberOfWorkersPerQueue` method in `src/AutoScaler.php`:

```php
            } elseif ($timeToClearAll == 0 &&
                      $supervisor->options->autoScaling()) {
                return [$queue => $supervisor->options->minProcesses];
            }
```

If `$timeToClearAll` is 0, it won't scale beyond the minimum number of processes. So where does `$timeToClearAll` come from? It's the sum of individual times to clear every separate queue, which are calculated in `timeToClearPerQueue`:

```php
            return [$queue => ($size * $this->metrics->runtimeForQueue($queue))];
```

The time to clear the queue depends on the runtime metric for the queue, but the metric will be empty until the first job finishes. As a result `$timeToClearAll` will be 0, so we'll be stuck at the minimum number of workers until the first job is done. If we set the minimum to 0, the first job will never be done, so this queue will be basically non-functional (unless it executed jobs while it was initially scaling down and still had workers).

### A potential solution

This could probably be fixed by sending information about queue sizes to `numberOfWorkersPerQueue` and scaling towards the maximum if we don't have the metrics yet but there are jobs waiting:

```php
            } elseif ($timeToClearAll == 0 &&
                      $supervisor->options->autoScaling()) {
                return [
                    $queue => $sizes[$queue] > 0
                        ? $supervisor->options->maxProcesses
                        : $supervisor->options->minProcesses
                ];
            }
```

I'm not sure if scaling towards maximum could result in creating too many workers. It will get corrected as soon as at least one job finishes. What do you guys think?

Here's a full AutoScaler.php needed to test this potential fix:
https://gist.github.com/rafalglowacz/702dfb92651130e23f5caa9d5a814247

**Comment by graemlourens** [comment] 2019-11-26 10:54
We are seeing the same behaviour with following setup:
Horizon Version: v3.4.2
Laravel Version: v6.0.3
PHP Version: 7.2.23
Redis Driver & Version: phpredis 5.1.1

If we have a queue with 0 minProcesses, that queue will never scale, it just stays like that forever. In some cases it indeed starts scaling, but only if we restart horizon and in 'bootup' (when several processes are initially spawned) and first job is processed. After that it works, but like Rafal mentioned, only when the first job completed.

**Comment by graemlourens** [comment] 2019-12-04 16:31
@driesvints is it intended to stay labelled as 'needs more info' ? We're able to reproduce this every time (as described by rafal and myself), and as the option exists for having minProcesses to be set to 0 i would tend to declare this as a bug. 
Hoping for your input.

**Comment by driesvints** [comment] 2019-12-05 15:31
@graemlourens unfortunately I don't have time to deep dive into this atm. If you really believe this is a bug then the best thing you can do atm is send in a PR to fix the broken behavior and let it be reviewed by Taylor.

**Comment by themsaid** [comment] 2019-12-06 09:38
A fix is proposed in https://github.com/laravel/horizon/pull/718

**Comment by graemlourens** [comment] 2019-12-06 11:05
@themsaid thank you very much for that PR. We tried out the changes and they work as intended. Hopefully this will get merged soon. I would still however have classified this as a bug, and not an enhancement.

**Comment by driesvints** [comment] 2019-12-06 15:30
PR was merged. Thanks for reporting.

**Closed by driesvints** 2019-12-06 15:30 UTC
Labels: bug
